// Bateria de Perguntas para o 1º Ano
// Cada nível tem um 'pool' grande de perguntas. O jogo vai sortear 10 em cada jogada.

const bancoPerguntas =[
    {
        nome: "A Planície (Até 10)",
        icone: "⛺",
        classeCSS: "tema-0",
        perguntasPool:[
            { q: "Quantas maçãs estão aqui?", v: "🍎🍎🍎🍎🍎", opts: ["4", "5", "6"], ans: "5" },
            { q: "Resolve a conta:", v: "🐶🐶 + 🐶 = ?", opts: ["2", "3", "4"], ans: "3" },
            { q: "Rebentou um balão! Quantos sobraram?", v: "🎈🎈🎈<span class='riscado'>🎈</span>", opts: ["3", "4", "2"], ans: "3" },
            { q: "Onde há mais peixes?", v: "🐟🐟🐟 ... 🐟🐟🐟🐟🐟", opts: ["Esquerda", "Direita", "Igual"], ans: "Direita" },
            { q: "Qual é o número escondido?", v: "1, 2, 3, ❓, 5", opts: ["4", "6", "0"], ans: "4" },
            { q: "Soma os carros:", v: "🚗🚗🚗 + 🚗🚗 = ?", opts:["4", "5", "6"], ans: "5" },
            { q: "Tinha 8 bolas, perdi 3. Fico com...", v: "⚽⚽⚽⚽⚽ <span class='riscado'>⚽⚽⚽</span>", opts: ["4", "5", "6"], ans: "5" },
            { q: "Que número é este: SETE", v: "", opts: ["6", "7", "8"], ans: "7" },
            { q: "Conta as estrelas:", v: "⭐ ⭐ ⭐ ⭐ ⭐<br>⭐ ⭐ ⭐ ⭐", opts: ["8", "9", "10"], ans: "9" },
            { q: "O número 5 é maior que o número...", v: "", opts: ["6", "4", "8"], ans: "4" },
            { q: "Qual é o resultado?", v: "5 + 5 = ?", opts:["9", "10", "8"], ans: "10" },
            { q: "Conta os morangos:", v: "🍓🍓<br>🍓🍓", opts: ["3", "4", "5"], ans: "4" },
            { q: "Tinha 5 flores, dei 1. Quantas sobraram?", v: "🌻🌻🌻🌻<span class='riscado'>🌻</span>", opts: ["4", "5", "3"], ans: "4" },
            { q: "Qual é o número que falta?", v: "8, 9, ❓", opts:["10", "7", "11"], ans: "10" },
            { q: "O número 8 é [ ? ] que o 10.", v: "8 ___ 10", opts:["Maior", "Menor", "Igual"], ans: "Menor" },
            { q: "Quantos lápis faltam para ter 10?", v: "Temos 8 lápis.", opts:["1", "2", "3"], ans: "2" },
            { q: "Conta os ursos:", v: "🧸🧸🧸🧸<br>🧸🧸🧸", opts: ["6", "7", "8"], ans: "7" },
            { q: "Soma as pizzas:", v: "🍕🍕🍕 + 🍕🍕🍕 = ?", opts:["5", "6", "7"], ans: "6" },
            { q: "Que número é este: NOVE", v: "", opts: ["8", "9", "6"], ans: "9" },
            { q: "Resolve a conta:", v: "10 - 5 = ?", opts: ["5", "6", "4"], ans: "5" },
            { q: "Se eu tiver 0 maçãs e me derem 4...", v: "Fico com:", opts: ["0", "4", "5"], ans: "4" },
            { q: "Qual o número antes do 3?", v: "❓, 3, 4", opts:["1", "2", "5"], ans: "2" }
        ]
    },
    {
        nome: "A Floresta (Até 20)",
        icone: "🌲",
        classeCSS: "tema-1",
        perguntasPool:[
            { q: "1 Dezena e 2 Unidades forma o número:", v: "🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩 <br> 🟨🟨", opts:["12", "21", "3"], ans: "12" },
            { q: "Resolve o cálculo mental:", v: "10 + 5 = ?", opts:["15", "50", "16"], ans: "15" },
            { q: "Resolve a subtração:", v: "15 - 3 = ?", opts: ["12", "13", "11"], ans: "12" },
            { q: "Descobre a sequência:", v: "14, 15, ❓, 17", opts: ["16", "18", "13"], ans: "16" },
            { q: "Qual é o número que vem antes do 20?", v: "❓ ... 20", opts: ["18", "19", "21"], ans: "19" },
            { q: "Qual é o dobro de 5?", v: "5 + 5 = ?", opts: ["15", "10", "55"], ans: "10" },
            { q: "Qual é a metade de 10?", v: "10 a dividir por 2 = ?", opts: ["5", "20", "2"], ans: "5" },
            { q: "O número 18 é [ ? ] que o 14.", v: "18 ___ 14", opts: ["Maior", "Menor", "Igual"], ans: "Maior" },
            { q: "Faz a conta:", v: "8 + 4 = ?", opts: ["11", "12", "13"], ans: "12" },
            { q: "Junta os números:", v: "10 + 9 = ?", opts: ["19", "91", "109"], ans: "19" },
            { q: "Conta de 2 em 2:", v: "12, 14, 16, ❓", opts: ["17", "18", "20"], ans: "18" },
            { q: "Que número é: QUINZE", v: "", opts:["15", "50", "5"], ans: "15" },
            { q: "Qual o resultado?", v: "20 - 10 = ?", opts: ["10", "5", "30"], ans: "10" },
            { q: "1 Dezena e 8 Unidades é o número:", v: "", opts:["81", "18", "8"], ans: "18" },
            { q: "Tinha 12 doces, comi 2. Fiquei com...", v: "", opts:["14", "10", "8"], ans: "10" },
            { q: "O que vem depois do 11?", v: "10, 11, ❓", opts: ["12", "13", "9"], ans: "12" },
            { q: "Junta mais:", v: "11 + 3 = ?", opts:["13", "14", "15"], ans: "14" },
            { q: "Qual destes números é PAR?", v: "", opts: ["13", "14", "15"], ans: "14" },
            { q: "Soma:", v: "10 + 10 = ?", opts:["10", "20", "0"], ans: "20" },
            { q: "O número escondido é:", v: "17, 18, ❓, 20", opts:["16", "21", "19"], ans: "19" },
            { q: "Subtrai:", v: "16 - 4 = ?", opts: ["12", "10", "14"], ans: "12" },
            { q: "Qual destes números é ÍMPAR?", v: "", opts:["12", "15", "18"], ans: "15" }
        ]
    },
    {
        nome: "As Nuvens (Até 50)",
        icone: "☁️",
        classeCSS: "tema-2",
        perguntasPool:[
            { q: "3 Dezenas e 5 Unidades é...", v: "", opts: ["53", "35", "8"], ans: "35" },
            { q: "Conta de 2 em 2:", v: "20, 22, 24, ❓", opts: ["25", "26", "28"], ans: "26" },
            { q: "Soma as dezenas:", v: "20 + 10 = ?", opts: ["30", "40", "21"], ans: "30" },
            { q: "Tira 10:", v: "40 - 10 = ?", opts: ["30", "50", "20"], ans: "30" },
            { q: "O número 45 é [ ? ] que o 32.", v: "45 ___ 32", opts: ["Maior", "Menor", "Igual"], ans: "Maior" },
            { q: "Continua a contar:", v: "40, 41, 42, ❓", opts: ["43", "44", "39"], ans: "43" },
            { q: "O Rui tinha 20 cartas e ganhou 5. Ficou com:", v: "", opts: ["20", "25", "30"], ans: "25" },
            { q: "O número a seguir ao 39 é o...", v: "39 ... ❓", opts: ["38", "40", "41"], ans: "40" },
            { q: "Cálculo Rápido:", v: "25 + 5 = ?", opts: ["30", "35", "20"], ans: "30" },
            { q: "Qual é o número 'quarenta e dois'?", v: "", opts:["24", "42", "402"], ans: "42" },
            { q: "Conta de 5 em 5:", v: "10, 15, 20, ❓", opts:["25", "30", "21"], ans: "25" },
            { q: "Soma:", v: "30 + 10 = ?", opts: ["20", "40", "50"], ans: "40" },
            { q: "Que número é este: VINTE E NOVE", v: "", opts:["29", "92", "39"], ans: "29" },
            { q: "Quantas dezenas tem o número 40?", v: "", opts: ["4", "0", "40"], ans: "4" },
            { q: "Qual é o número antes do 30?", v: "❓ ... 30", opts:["31", "29", "28"], ans: "29" },
            { q: "Metade de 20 é:", v: "", opts: ["10", "5", "15"], ans: "10" },
            { q: "Soma de dezenas:", v: "10 + 10 + 10 = ?", opts: ["20", "30", "40"], ans: "30" },
            { q: "Qual é maior?", v: "38 ou 41?", opts:["38", "41", "Iguais"], ans: "41" },
            { q: "O que vem na sequência:", v: "47, 48, 49, ❓", opts:["40", "50", "51"], ans: "50" },
            { q: "Subtração simples:", v: "25 - 5 = ?", opts: ["15", "20", "30"], ans: "20" },
            { q: "4 Dezenas e 9 Unidades forma o:", v: "", opts: ["94", "409", "49"], ans: "49" }
        ]
    },
    {
        nome: "O Topo da Montanha (Até 100)",
        icone: "🏔️",
        classeCSS: "tema-3",
        perguntasPool:[
            { q: "Cálculo Mental:", v: "50 + 20 = ?", opts: ["60", "70", "80"], ans: "70" },
            { q: "Atenção! Qual é o número maior?", v: "79 ou 97?", opts: ["79", "97", "89"], ans: "97" },
            { q: "8 Dezenas e 0 Unidades é o número:", v: "", opts:["8", "80", "800"], ans: "80" },
            { q: "Conta de 10 em 10:", v: "50, 60, 70, ❓", opts: ["80", "75", "90"], ans: "80" },
            { q: "O número 99 está quase a chegar ao...", v: "98, 99, ❓", opts: ["90", "100", "80"], ans: "100" },
            { q: "Subtração rápida:", v: "100 - 10 = ?", opts: ["90", "80", "10"], ans: "90" },
            { q: "Qual é a metade de 100?", v: "", opts:["50", "40", "60"], ans: "50" },
            { q: "Faltam 5 páginas para acabar um livro de 100 páginas. Em que página estou?", v: "", opts: ["90", "95", "105"], ans: "95" },
            { q: "Decomposição:", v: "60 + 5 + 2 = ?", opts:["67", "72", "65"], ans: "67" },
            { q: "Que número é este: NOVENTA E NOVE", v: "", opts: ["66", "99", "109"], ans: "99" },
            { q: "Soma de dezenas:", v: "40 + 40 = ?", opts: ["60", "70", "80"], ans: "80" },
            { q: "Qual é o dobro de 50?", v: "", opts:["25", "100", "75"], ans: "100" },
            { q: "Conta de 5 em 5:", v: "85, 90, 95, ❓", opts:["100", "96", "99"], ans: "100" },
            { q: "Qual vem depois do 89?", v: "88, 89, ❓", opts:["80", "90", "91"], ans: "90" },
            { q: "Subtrai:", v: "80 - 20 = ?", opts: ["60", "50", "70"], ans: "60" },
            { q: "Decomposição:", v: "90 + 3 = ?", opts:["39", "93", "903"], ans: "93" },
            { q: "Que número é: OITENTA E OITO", v: "", opts: ["80", "18", "88"], ans: "88" },
            { q: "O número 75 tem quantas dezenas?", v: "", opts:["7", "5", "75"], ans: "7" },
            { q: "O que é menor?", v: "64 ou 46?", opts: ["64", "46", "Iguais"], ans: "46" },
            { q: "Faltam 20 para 100. Eu tenho:", v: "100 - 20 = ?", opts: ["80", "70", "90"], ans: "80" },
            { q: "Soma rápida:", v: "50 + 50 = ?", opts:["50", "0", "100"], ans: "100" }
        ]
    }
];
