const palavras = [

    { palavra: "pato",     silabas: ["pa", "to"],                       imagem: "img/pato.png" },
    { palavra: "gato",     silabas: ["ga", "to"],                       imagem: "img/gato.png" },
    { palavra: "bola",     silabas: ["bo", "la"],                       imagem: "img/bola.png" },
    { palavra: "vaca",     silabas: ["va", "ca"],                       imagem: "img/vaca.png" },
    { palavra: "ratito",   silabas: ["ra", "ti", "to"],                 imagem: "img/ratito.png" },
    { palavra: "violino",  silabas: ["vi", "o", "li", "no"],            imagem: "img/violino.png" },
    { palavra: "melão",    silabas: ["me", "lão"],                      imagem: "img/melao.png" },
    { palavra: "mota",     silabas: ["mo", "ta"],                       imagem: "img/mota.png" },
    { palavra: "janela",   silabas: ["ja", "ne", "la"],                 imagem: "img/janela.png" },
    { palavra: "jipe",     silabas: ["ji", "pe"],                       imagem: "img/jipe.png" },
    { palavra: "cama",     silabas: ["ca", "ma"],                       imagem: "img/cama.png" },
    { palavra: "dado",     silabas: ["da", "do"],                       imagem: "img/dado.png" },
    { palavra: "baleia",   silabas: ["ba", "lei", "a"],                 imagem: "img/baleia.png" },
    { palavra: "vela",     silabas: ["ve", "la"],                       imagem: "img/vela.png" },
    { palavra: "mala",     silabas: ["ma", "la"],                       imagem: "img/mala.png" },
    { palavra: "macaco",   silabas: ["ma", "ca", "co"],                 imagem: "img/macaco.png" },
    { palavra: "dedo",     silabas: ["de", "do"],                       imagem: "img/dedo.png" },
    { palavra: "cavalo",   silabas: ["ca", "va", "lo"],                 imagem: "img/cavalo.png" },
    { palavra: "limão",    silabas: ["li", "mão"],                      imagem: "img/limao.png" },
    { palavra: "foca",     silabas: ["fo", "ca"],                       imagem: "img/foca.png" },
    { palavra: "papagaio", silabas: ["pa", "pa", "gai", "o"],           imagem: "img/papagaio.png" },
    { palavra: "avião",    silabas: ["a", "vi", "ão"],                  imagem: "img/aviao.png" },
    { palavra: "pote",     silabas: ["po", "te"],                       imagem: "img/pote.png" },
    { palavra: "tomate",   silabas: ["to", "ma", "te"],                 imagem: "img/tomate.png" },
    { palavra: "banana",   silabas: ["ba", "na", "na"],                 imagem: "img/banana.png" },
    { palavra: "amarelo",  silabas: ["a", "ma", "re", "lo"],            imagem: "img/amarelo.png" },
    { palavra: "roda",     silabas: ["ro", "da"],                       imagem: "img/roda.png" },
    { palavra: "bota",     silabas: ["bo", "ta"],                       imagem: "img/bota.png" },
    { palavra: "mapa",     silabas: ["ma", "pa"],                       imagem: "img/mapa.png" },
    { palavra: "fada",     silabas: ["fa", "da"],                       imagem: "img/fada.png" }
    { palavra: "boneca",   silabas: ["bo", "ne", "ca"],                 imagem: "img/boneca.png" }

];
