const palavras = [
  { palavra: "pato", imagem: "img/pato.png", num: 2, divisao: "PA - TO" },
  { palavra: "gato", imagem: "img/gato.png", num: 2, divisao: "GA - TO" },
  { palavra: "bola", imagem: "img/bola.png", num: 2, divisao: "BO - LA" },
  { palavra: "vaca", imagem: "img/vaca.png", num: 2, divisao: "VA - CA" },
  { palavra: "rato", imagem: "img/rato.png", num: 2, divisao: "RA - TO" },
  { palavra: "violino", imagem: "img/violino.png", num: 4, divisao: "VI - O - LI - NO" },
  { palavra: "melão", imagem: "img/melao.png", num: 2, divisao: "ME - LÃO" },
  { palavra: "mota", imagem: "img/mota.png", num: 2, divisao: "MO - TA" },
  { palavra: "janela", imagem: "img/janela.png", num: 3, divisao: "JA - NE - LA" },
  { palavra: "jipe", imagem: "img/jipe.png", num: 2, divisao: "JI - PE" },
  { palavra: "cama", imagem: "img/cama.png", num: 2, divisao: "CA - MA" },
  { palavra: "tartaruga", imagem: "img/tartaruga.png", num: 4, divisao: "TAR - TA - RU - GA" },
  { palavra: "dado", imagem: "img/dado.png", num: 2, divisao: "DA - DO" },
  { palavra: "baleia", imagem: "img/baleia.png", num: 3, divisao: "BA - LEI - A" },
  { palavra: "vela", imagem: "img/vela.png", num: 2, divisao: "VE - LA" },
  { palavra: "abelha", imagem: "img/abelha.png", num: 3, divisao: "A - BE - LHA" },
  { palavra: "autocarro", imagem: "img/autocarro.png", num: 4, divisao: "AU - TO - CAR - RO" },
  { palavra: "bicicleta", imagem: "img/bicicleta.png", num: 4, divisao: "BI - CI - CLE - TA" },
  { palavra: "cenoura", imagem: "img/cenoura.png", num: 3, divisao: "CE - NOU - RA" },
  { palavra: "maçã", imagem: "img/maca.png", num: 2, divisao: "MA - ÇÃ" },
  { palavra: "livro", imagem: "img/livro.png", num: 2, divisao: "LI - VRO" },
  { palavra: "queijo", imagem: "img/queijo.png", num: 2, divisao: "QUEI - JO" },
  { palavra: "óculos", imagem: "img/oculos.png", num: 3, divisao: "Ó - CU - LOS" },
  { palavra: "casaco", imagem: "img/casaco.png", num: 3, divisao: "CA - SA - CO" },
  { palavra: "tesoura", imagem: "img/tesoura.png", num: 3, divisao: "TE - SOU - RA" },
  { palavra: "palhaço", imagem: "img/palhaco.png", num: 3, divisao: "PA - LHA - ÇO" },
  { palavra: "ovelha", imagem: "img/ovelha.png", num: 3, divisao: "O - VE - LHA" },
  { palavra: "mala", imagem: "img/mala.png", num: 2, divisao: "MA - LA" },
  { palavra: "macaco", imagem: "img/macaco.png", num: 3, divisao: "MA - CA - CO" },
  { palavra: "dedo", imagem: "img/dedo.png", num: 2, divisao: "DE - DO" },
  { palavra: "cavalo", imagem: "img/cavalo.png", num: 3, divisao: "CA - VA - LO" },
  { palavra: "limão", imagem: "img/limao.png", num: 2, divisao: "LI - MÃO" },
  { palavra: "foca", imagem: "img/foca.png", num: 2, divisao: "FO - CA" },
  { palavra: "papagaio", imagem: "img/papagaio.png", num: 4, divisao: "PA - PA - GAI - O" },
  { palavra: "avião", imagem: "img/aviao.png", num: 3, divisao: "A - VI - ÃO" },
  { palavra: "pote", imagem: "img/pote.png", num: 2, divisao: "PO - TE" },
  { palavra: "tomate", imagem: "img/tomate.png", num: 3, divisao: "TO - MA - TE" },
  { palavra: "banana", imagem: "img/banana.png", num: 3, divisao: "BA - NA - NA" },
  { palavra: "amarelo", imagem: "img/amarelo.png", num: 4, divisao: "A - MA - RE - LO" },
  { palavra: "roda", imagem: "img/roda.png", num: 2, divisao: "RO - DA" },
  { palavra: "bota", imagem: "img/bota.png", num: 2, divisao: "BO - TA" },
  { palavra: "mapa", imagem: "img/mapa.png", num: 2, divisao: "MA - PA" },
  { palavra: "fada", imagem: "img/fada.png", num: 2, divisao: "FA - DA" },
  { palavra: "boneca", imagem: "img/boneca.png", num: 3, divisao: "BO - NE - CA" },
  { palavra: "batata", imagem: "img/batata.png", num: 3, divisao: "BA - TA - TA" },
  { palavra: "girafa", imagem: "img/girafa.png", num: 3, divisao: "GI - RA - FA" },
  { palavra: "cadeira", imagem: "img/cadeira.png", num: 3, divisao: "CA - DEI - RA" },
  { palavra: "caracol", imagem: "img/caracol.png", num: 3, divisao: "CA - RA - COL" },
  { palavra: "piano", imagem: "img/piano.png", num: 3, divisao: "PI - A - NO" }
];
