const palavras = [
  // PALAVRAS ORIGINAIS (Atualizadas com Sílabas e Lacunas)
  { palavra: "pato", imagem: "img/pato.png", num: 2, divisao: "PA - TO", falta: "_ato", correta: "p", opcoes: ["p", "g", "r"] },
  { palavra: "gato", imagem: "img/gato.png", num: 2, divisao: "GA - TO", falta: "_ato", correta: "g", opcoes: ["g", "p", "m"] },
  { palavra: "bola", imagem: "img/bola.png", num: 2, divisao: "BO - LA", falta: "bo_a", correta: "l", opcoes: ["l", "t", "m"] },
  { palavra: "vaca", imagem: "img/vaca.png", num: 2, divisao: "VA - CA", falta: "_aca", correta: "v", opcoes: ["v", "f", "p"] },
  { palavra: "rato", imagem: "img/ratito.png", num: 2, divisao: "RA - TO", falta: "_ato", correta: "r", opcoes: ["r", "p", "g"] },
  { palavra: "violino", imagem: "img/violino.png", num: 4, divisao: "VI - O - LI - NO", falta: "vio_ino", correta: "l", opcoes: ["l", "n", "t"] },
  { palavra: "melão", imagem: "img/melao.png", num: 2, divisao: "ME - LÃO", falta: "me_ão", correta: "l", opcoes: ["l", "m", "n"] },
  { palavra: "mota", imagem: "img/mota.png", num: 2, divisao: "MO - TA", falta: "_ota", correta: "m", opcoes: ["m", "b", "p"] },
  { palavra: "janela", imagem: "img/janela.png", num: 3, divisao: "JA - NE - LA", falta: "ja_ela", correta: "n", opcoes: ["n", "m", "l"] },
  { palavra: "jipe", imagem: "img/jipe.png", num: 2, divisao: "JI - PE", falta: "ji_e", correta: "p", opcoes: ["p", "t", "b"] },
  { palavra: "cama", imagem: "img/cama.png", num: 2, divisao: "CA - MA", falta: "ca_a", correta: "m", opcoes: ["m", "n", "l"] },
  { palavra: "tartaruga", imagem: "img/tartaruga.png", num: 4, divisao: "TAR - TA - RU - GA", falta: "tarta_uga", correta: "r", opcoes: ["r", "l", "m"] },
  { palavra: "dado", imagem: "img/dado.png", num: 2, divisao: "DA - DO", falta: "_ado", correta: "d", opcoes: ["d", "t", "b"] },
  { palavra: "baleia", imagem: "img/baleia.png", num: 3, divisao: "BA - LEI - A", falta: "ba_eia", correta: "l", opcoes: ["l", "n", "r"] },
  { palavra: "vela", imagem: "img/vela.png", num: 2, divisao: "VE - LA", falta: "_ela", correta: "v", opcoes: ["v", "m", "b"] },
  { palavra: "abelha", imagem: "img/abelha.png", num: 3, divisao: "A - BE - LHA", falta: "abe_ha", correta: "l", opcoes: ["l", "t", "r"] },
  { palavra: "autocarro", imagem: "img/autocarro.png", num: 4, divisao: "AU - TO - CAR - RO", falta: "autoca_ro", correta: "r", opcoes: ["r", "s", "l"] },
  { palavra: "bicicleta", imagem: "img/bicicleta.png", num: 4, divisao: "BI - CI - CLE - TA", falta: "bici_leta", correta: "c", opcoes: ["c", "q", "s"] },
  { palavra: "cenoura", imagem: "img/cenoura.png", num: 3, divisao: "CE - NOU - RA", falta: "_enoura", correta: "c", opcoes: ["c", "s", "z"] },
  { palavra: "maçã", imagem: "img/maca.png", num: 2, divisao: "MA - ÇÃ", falta: "ma_ã", correta: "ç", opcoes: ["ç", "s", "c"] },
  { palavra: "livro", imagem: "img/livro.png", num: 2, divisao: "LI - VRO", falta: "li_ro", correta: "v", opcoes: ["v", "f", "p"] },
  { palavra: "queijo", imagem: "img/queijo.png", num: 2, divisao: "QUEI - JO", falta: "quei_o", correta: "j", opcoes: ["j", "g", "x"] },
  { palavra: "óculos", imagem: "img/oculos.png", num: 3, divisao: "Ó - CU - LOS", falta: "ó_ulos", correta: "c", opcoes: ["c", "q", "g"] },
  { palavra: "casaco", imagem: "img/casaco.png", num: 3, divisao: "CA - SA - CO", falta: "ca_aco", correta: "s", opcoes: ["s", "z", "x"] },
  { palavra: "tesoura", imagem: "img/tesoura.png", num: 3, divisao: "TE - SOU - RA", falta: "te_oura", correta: "s", opcoes: ["s", "z", "x"] },
  { palavra: "palhaço", imagem: "img/palhaco.png", num: 3, divisao: "PA - LHA - ÇO", falta: "pa_haço", correta: "l", opcoes: ["l", "t", "n"] },
  { palavra: "ovelha", imagem: "img/ovelha.png", num: 3, divisao: "O - VE - LHA", falta: "ove_ha", correta: "l", opcoes: ["l", "t", "r"] },
  { palavra: "mala", imagem: "img/mala.png", num: 2, divisao: "MA - LA", falta: "_ala", correta: "m", opcoes: ["m", "f", "p"] },
  { palavra: "macaco", imagem: "img/macaco.png", num: 3, divisao: "MA - CA - CO", falta: "ma_aco", correta: "c", opcoes: ["c", "g", "q"] },
  { palavra: "dedo", imagem: "img/dedo.png", num: 2, divisao: "DE - DO", falta: "_edo", correta: "d", opcoes: ["d", "b", "t"] },
  { palavra: "cavalo", imagem: "img/cavalo.png", num: 3, divisao: "CA - VA - LO", falta: "ca_alo", correta: "v", opcoes: ["v", "f", "b"] },
  { palavra: "limão", imagem: "img/limao.png", num: 2, divisao: "LI - MÃO", falta: "li_ão", correta: "m", opcoes: ["m", "n", "l"] },
  { palavra: "foca", imagem: "img/foca.png", num: 2, divisao: "FO - CA", falta: "_oca", correta: "f", opcoes: ["f", "v", "p"] },
  { palavra: "papagaio", imagem: "img/papagaio.png", num: 4, divisao: "PA - PA - GAI - O", falta: "papa_aio", correta: "g", opcoes: ["g", "j", "q"] },
  { palavra: "avião", imagem: "img/aviao.png", num: 3, divisao: "A - VI - ÃO", falta: "a_ião", correta: "v", opcoes: ["v", "f", "b"] },
  { palavra: "pote", imagem: "img/pote.png", num: 2, divisao: "PO - TE", falta: "_ote", correta: "p", opcoes: ["p", "b", "m"] },
  { palavra: "tomate", imagem: "img/tomate.png", num: 3, divisao: "TO - MA - TE", falta: "to_ate", correta: "m", opcoes: ["m", "n", "l"] },
  { palavra: "banana", imagem: "img/banana.png", num: 3, divisao: "BA - NA - NA", falta: "_anana", correta: "b", opcoes: ["b", "p", "d"] },
  { palavra: "amarelo", imagem: "img/amarelo.png", num: 4, divisao: "A - MA - RE - LO", falta: "ama_elo", correta: "r", opcoes: ["r", "l", "m"] },
  { palavra: "roda", imagem: "img/roda.png", num: 2, divisao: "RO - DA", falta: "_oda", correta: "r", opcoes: ["r", "m", "f"] },
  { palavra: "bota", imagem: "img/bota.png", num: 2, divisao: "BO - TA", falta: "_ota", correta: "b", opcoes: ["b", "m", "p"] },
  { palavra: "mapa", imagem: "img/mapa.png", num: 2, divisao: "MA - PA", falta: "_apa", correta: "m", opcoes: ["m", "p", "c"] },
  { palavra: "fada", imagem: "img/fada.png", num: 2, divisao: "FA - DA", falta: "_ada", correta: "f", opcoes: ["f", "v", "p"] },
  { palavra: "boneca", imagem: "img/boneca.png", num: 3, divisao: "BO - NE - CA", falta: "bo_eca", correta: "n", opcoes: ["n", "m", "l"] },
  { palavra: "batata", imagem: "img/batata.png", num: 3, divisao: "BA - TA - TA", falta: "_atata", correta: "b", opcoes: ["b", "p", "d"] },
  { palavra: "girafa", imagem: "img/girafa.png", num: 3, divisao: "GI - RA - FA", falta: "gi_afa", correta: "r", opcoes: ["r", "l", "m"] },
  { palavra: "cadeira", imagem: "img/cadeira.png", num: 3, divisao: "CA - DEI - RA", falta: "ca_eira", correta: "d", opcoes: ["d", "t", "b"] },
  { palavra: "caracol", imagem: "img/caracol.png", num: 3, divisao: "CA - RA - COL", falta: "cara_ol", correta: "c", opcoes: ["c", "q", "g"] },
  { palavra: "piano", imagem: "img/piano.png", num: 3, divisao: "PI - A - NO", falta: "_iano", correta: "p", opcoes: ["p", "b", "t"] },

  // NOVAS ADIÇÕES (Pares Mínimos e Fonemas do 1º Ano)
  { palavra: "sapo", imagem: "img/sapo.png", num: 2, divisao: "SA - PO", falta: "_apo", correta: "s", opcoes: ["s", "z", "p"] },
  { palavra: "lupa", imagem: "img/lupa.png", num: 2, divisao: "LU - PA", falta: "lu_a", correta: "p", opcoes: ["p", "m", "t"] },
  { palavra: "mesa", imagem: "img/mesa.png", num: 2, divisao: "ME - SA", falta: "_esa", correta: "m", opcoes: ["m", "p", "n"] },
  { palavra: "sino", imagem: "img/sino.png", num: 2, divisao: "SI - NO", falta: "_ino", correta: "s", opcoes: ["s", "z", "p"] },
  { palavra: "fala", imagem: "img/fala.png", num: 2, divisao: "FA - LA", falta: "_ala", correta: "f", opcoes: ["f", "m", "p"] }, // Par com Mala
  { palavra: "carro", imagem: "img/carro.png", num: 2, divisao: "CAR - RO", falta: "ca_ro", correta: "r", opcoes: ["r", "s", "l"] },
  { palavra: "chave", imagem: "img/chave.png", num: 2, divisao: "CHA - VE", falta: "_have", correta: "c", opcoes: ["c", "q", "g"] }
];
